- name: "Execute war file on Tomcat Server"
  hosts: WEB
  become: true
  vars:
    gitdir: "/tmp/addressbook-project-1"
  tasks:
    - name: "install maven"
      apt:
        update-cache: "yes"
        name: "maven"
        state: "present"
        
    - name: "Install tomcat9"
      apt: 
        update-cache: "yes"
        name: "tomcat9"
        state: "present"

    - name: "clone the repository"
      git:
        repo: "https://github.com/upshiftnow/addressbook"
        dest: "{{gitdir}}"
        version: "master"

    - name: "compile the addressbook project"
      command:
        chdir: "{{gitdir}}"
        cmd: "mvn package"

    - name: "Deploy WAR File"
      copy:
        src: "{{gitdir}}/target/addressbook-2.0.war"
        dest: "/var/lib/tomcat9/webapps/addressbook.war"
        remote_src: "yes"
    
    - name: "Stop tomcat9"
      service: 
        name: "tomcat9"
        state: "stopped"

    - name: "Start tomcat9"
      service: 
        name: "tomcat9"
        state: "started"
        enable: "yes"
    
